services:
  gdpr-app:
    build: .
    container_name: gdpr-python-app
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./:/app:rw   # Speglar hela projektmappen till /app i containern



